;; Color Theme
(require 'color-theme)

(defun color-theme-wat ()
  (interactive)
  (color-theme-install
   '(color-theme-wat
      ((background-color . "#000000")
      (background-mode . light)
      (border-color . "#3b3b3b")
      (cursor-color . "#ffffff")
      (foreground-color . "#ffd442")
      (mouse-color . "black"))
     (fringe ((t (:background "#3b3b3b"))))
     (mode-line ((t (:foreground "#d3f3e7" :background "#5e0402"))))
     (region ((t (:background "#ffffff"))))
     (font-lock-builtin-face ((t (:foreground "#72cccf"))))
     (font-lock-comment-face ((t (:foreground "#64a208"))))
     (font-lock-function-name-face ((t (:foreground "#069864"))))
     (font-lock-keyword-face ((t (:foreground "#6283cb"))))
     (font-lock-string-face ((t (:foreground "#b30010"))))
     (font-lock-type-face ((t (:foreground"#e43dff"))))
     (font-lock-constant-face ((t (:foreground "#ff9924"))))
     (font-lock-variable-name-face ((t (:foreground "#fd9168"))))
     (minibuffer-prompt ((t (:foreground "#ffffff" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))

(provide 'color-theme-wat)

(defun color-theme-xenburn ()
  (interactive)
  (color-theme-install
   '(color-theme-xenburn
      ((background-color . "#2b2b2b")
      (background-mode . light)
      (border-color . "#3b3b3b")
      (cursor-color . "#aaaaaa")
      (foreground-color . "#ddb739")
      (mouse-color . "black"))
     (fringe ((t (:background "#3b3b3b"))))
     (mode-line ((t (:foreground "#e2e9c9" :background "#3e1211"))))
     (region ((t (:background "#444444"))))
     (font-lock-builtin-face ((t (:foreground "#79d8dc"))))
     (font-lock-comment-face ((t (:foreground "#71a03a" :slant italic))))
     (font-lock-function-name-face ((t (:foreground "#49ada0"))))
     (font-lock-keyword-face ((t (:foreground "#a2a9ad" :weight bold))))
     (font-lock-string-face ((t (:foreground "#c04a55"))))
     (font-lock-type-face ((t (:foreground"#e18edf"))))
     (font-lock-constant-face ((t (:foreground "#ff9924"))))
     (font-lock-variable-name-face ((t (:foreground "#f6b78c"))))
     (minibuffer-prompt ((t (:foreground "#bfbfbf" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))

(provide 'color-theme-xenburn)
(require 'zenburn)

(color-theme-initialize)
(color-theme-aliceblue)
